- hosts: all
  tags: always
  pre_tasks:
    - name: Update cache (Debian family)
      become: true
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Install Updates (Debian family)
      become: true
      ansible.builtin.apt:
        upgrade: yes
      when: ansible_os_family == "Debian"
  roles:
    - bootstrap
