- hosts: all
  tags: always
  pre_tasks:
    - name: Update Cache (Debian family)
      become: true
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Update System (Debian family)
      become: true
      ansible.builtin.apt:
        upgrade: yes
      when: ansible_os_family == "Debian"

  roles:
    - core
