# cert-manager chart dependecy options
cert-manager:
  enabled: true
  crds:
    enabled: true
  extraArgs:
    - --enable-gateway-api

global:
  gateway:
    name: neftales-dev-tls
    className: cilium
  domain: neftales.dev
  dnsSecret:
    name: cloudflare-dns-token
    token: token
  clusterIssuer:
    name: "letsencrypt"
    email: neftales@gmail.com
