apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: grafana-http-route
spec:
  parentRefs:
    - name: {{ .Values.gatewayApi.name }}
      namespace: {{ .Values.gatewayApi.namespace }}
  hostnames:
    - {{ .Values.gatewayApi.hostnames.grafana }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ .Release.Name }}-grafana
          kind: Service
          port: 80
