services:
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    ports:
      - "3000"
    image: openspeedtest/latest
    networks:
      - private
networks:
  private:
    external: true
