secret:
  name: pihole-password
  password: password

external-dns:
  enabled: true
  rbac:
    # -- If `true`, create a `ClusterRole` & `ClusterRoleBinding` with access to the Kubernetes API.
    create: true
    # -- Additional rules to add to the `ClusterRole`.
    additionalPermissions: []

  # -- (int) Specify the number of old `ReplicaSets` to retain to allow rollback of the `Deployment``.
  revisionHistoryLimit: 3

  serviceMonitor:
    # -- If `true`, create a `ServiceMonitor` resource to support the _Prometheus Operator_.
    enabled: false
    # -- Additional labels for the `ServiceMonitor`.
    additionalLabels: {}
    # -- Annotations to add to the `ServiceMonitor`.
    annotations: {}
    # -- (string) If set create the `ServiceMonitor` in an alternate namespace.
    namespace:
    # -- (string) If set override the _Prometheus_ default interval.
    interval:
    # -- (string) If set override the _Prometheus_ default scrape timeout.
    scrapeTimeout:
    # -- (string) If set overrides the _Prometheus_ default scheme.
    scheme:
    # -- Configure the `ServiceMonitor` [TLS config](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#tlsconfig).
    tlsConfig: {}
    # -- (string) Provide a bearer token file for the `ServiceMonitor`.
    bearerTokenFile:
    # -- [Relabel configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) to apply to samples before ingestion.
    relabelings: []
    # -- [Metric relabel configs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs) to apply to samples before ingestion.
    metricRelabelings: []
    # -- Provide target labels for the `ServiceMonitor`.
    targetLabels: []

  env:
    - name: EXTERNAL_DNS_PIHOLE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pihole-password
          key: pihole-password

  # -- Log level.
  logLevel: debug

  # -- _Kubernetes_ resources to monitor for DNS entries.
  sources:
    - service
    - ingress
    - gateway-httproute

  # -- How DNS records are synchronized between sources and providers; available values are `sync` & `upsert-only`.
  policy: upsert-only

  # -- Specify the registry for storing ownership and labels.
  # Valid values are `txt`, `aws-sd`, `dynamodb` & `noop`.
  registry: noop

  provider:
    # -- _ExternalDNS_ provider name; for the available providers and how to configure them see [README](https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/README.md#providers).
    name: pihole

  # -- Extra arguments to provide to _ExternalDNS_.
  extraArgs:
    - --pihole-server=https://pihole.neftales.dev
