apiVersion: v2
name: argo-cd
description: ArgoCD instalation
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: argo-cd
    version: 7.7.0
    repository: https://argoproj.github.io/argo-helm
    alias: argocd
    condition: argocd.enabled
