argocd:
  enabled: true
  fullname: argocd
  global:
    domain: argocd.neftales.dev

  configs:
    params:
      server.insecure: true
    cm:
      create: true
      application.instanceLabelKey: app.kubernetes.io/instance

  server:
    ingress:
      enabled: false

gatewayApi:
  name: neftales-dev-tls
  namespace: cert-manager
  hostname: argocd.neftales.dev
