# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "proxmox" {
  endpoint  = var.proxmox_endpoint
  api_token = var.proxmox_api_token

  insecure = true

  ssh {
    agent       = true
    username    = var.proxmox_ssh_user
    private_key = file(var.proxmox_root_ssh_private_key)
  }
}
