apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.global.clusterIssuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.global.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ .Values.global.clusterIssuer.name }}
    solvers:
      - dns01:
          cloudflare:
            email: {{ .Values.global.clusterIssuer.email }}
            apiTokenSecretRef:
              name: {{ .Values.global.dnsSecret.name }}
              key: api-token
