apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.global.gateway.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.global.clusterIssuer.name }}
spec:
  gatewayClassName: {{ .Values.global.gateway.className }}
  listeners:
    - name: https
      protocol: HTTPS
      hostname: "*.{{ .Values.global.domain }}"
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: {{ .Values.global.domain }}-tls
