# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.dnsSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-token: {{ .Values.global.dnsSecret.token }}
