- name: Install core packages
  become: true
  ansible.builtin.apt:
    name:
      - vim
      - btop
      - unzip
      - git
      - curl
      - build-essential
      - silversearcher-ag
      - jq
    state: latest
  when: ansible_os_family == "Debian"
