apiVersion: v2
name: cilium
description: Cilium Helm Charts
type: application
version: 0.1.0
dependencies:
  - name: cilium
    version: 1.16.0
    repository: https://helm.cilium.io/
    condition: cilium.enabled
