cilium:
  enabled: true
  encryption:
    enabled: true
    type: wireguard
  gatewayAPI:
    enabled: true
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  ingressController:
    enabled: true
    loadbalancerMode: dedicated
  k8sServiceHost: 192.168.15.52
  k8sServicePort: 6443
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
