ciliumL2AnnouncementPolicy:
  name: basic-policy
  interface: enp1s0
  externalIPs: true
  loadBalancerIPs: true

ciliumLoadBalancerIPPool:
  name: pool-01
  cidr: "192.168.15.240/29"

cilium:
  enabled: true
  encryption:
    enabled: true
    type: wireguard
  gatewayAPI:
    enabled: true
  hubble:
    enabled: true
    metrics:
      enableOpenMetrics: true
      enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
      serviceMonitor:
        enabled: true
    relay:
      enabled: true
      prometheus:
        enabled: true
        port: 9966
        serviceMonitor:
          enabled: true
    ui:
      enabled: true
  ingressController:
    enabled: true
    loadbalancerMode: dedicated
  k8sServiceHost: 192.168.15.52
  k8sServicePort: 6443
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      trustCRDsExist: true
  operator:
    prometheus:
      enabled: true
