ciliumL2AnnouncementPolicy:
  name: basic-policy
  interface: enp1s0
  externalIPs: true
  loadBalancerIPs: true

ciliumLoadBalancerIPPool:
  name: pool-01
  cidr: "192.168.15.240/29"

cilium:
  enabled: true
  encryption:
    enabled: true
    type: wireguard
  gatewayAPI:
    enabled: true
  hubble:
    enabled: true
    metrics:
      enableOpenMetrics: true
      enabled:
        - dns
        - drop
        - tcp
        - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
        - "kafka:labelsContext=source_namespace,source_workload,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
        - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
        - port-distribution
        - icmp
        - http
        - "policy:sourceContext=app|workload-name|pod|reserved-identity;destinationContext=app|workload-name|pod|dns|reserved-identity;labelsContext=source_namespace,destination_namespace"
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus-stack
      dashboards:
        enabled: true
        namespace: monitoring
        annotations:
          grafana_folder: "Hubble"
    relay:
      enabled: true
      prometheus:
        enabled: true
        port: 9966
        serviceMonitor:
          enabled: true
          labels:
            release: prometheus-stack
    ui:
      enabled: true
  ingressController:
    enabled: true
    loadbalancerMode: dedicated
  k8sServiceHost: 192.168.15.52
  k8sServicePort: 6443
  kubeProxyReplacement: true
  l2announcements:
    enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus-stack
      trustCRDsExist: true
  operator:
    prometheus:
      enabled: true
