apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.argocd.fullname }}-http-route
spec:
  parentRefs:
    - name: {{ .Values.gatewayApi.name }}
      namespace: {{ .Values.gatewayApi.namespace }}
  hostnames:
    - {{ .Values.gatewayApi.hostname }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: argocd-server
          kind: Service
          port: 443
